# Generated by Django 4.0.5 on 2022-06-11 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='People',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.people'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='People',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.people'),
        ),
    ]
